import Aside from '@/components/Layout/Aside'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Container from '@/components/Layout/Container'
import InnerContent from '@/components/Layout/InnerContent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Aside />
          <InnerContent>
          {children}
          </InnerContent>
        </Container>
      </body>
    </html>
  );
}
